sudo: required
services:
  - docker

before_install:
  - docker build -t jfouriex/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run jfouriex/multi-docker npm test -- --coverage

after_success:
  - docker build -t jfouriex/multi-client ./client
  - docker build -t jfouriex/multi-nginx ./nginx
  - docker build -t jfouriex/multi-server ./server
  - docker build -t jfouriex/multi-worker ./worker 

    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jfouriex/multi-client
  - docker push jfouriex/multi-nginx
  - docker push jfouriex/multi-server
  - docker push jfouriex/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker-app"
  env: "MultiDockerApp-env"
  bucket_name: "elasticbeanstalk-eu-north-1-644429775120"
  bucket_path: "docker_multi"
  on: 
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  